### ISSUE TITLE
feature to stop after a certain number of steps

### ISSUE THREAD

**Issue by marijnheule** [hgarrereyn/SBVA#1]
I would like a feature to would terminate the algorithm after a certain number of variables is added. 

I would suggest adding a command-line option -s X would terminate the tool after introducing X variables.

**Comment by hgarrereyn** [comment]
Implemented in https://github.com/hgarrereyn/SBVA/commit/551e4a0d4d1bebecc107d69c04b9fe6eeb47d5a9

**Comment by marijnheule** [comment]
Thanks!

Marijn
