### ISSUE TITLE
Bug in checking of `fin` instead of `fproof`

### ISSUE THREAD

**Issue by msoos** [hgarrereyn/SBVA#4]
https://github.com/hgarrereyn/SBVA/blob/becc0e079bb3aeb77b7d2ef73f15c82667642250/sbva.cc#L866

This should be checking for `fproof` I believe?

**Comment by hgarrereyn** [comment]
oof yeah, gonna blame copilot for this one...

**Comment by msoos** [comment]
Nice! I am still new to this copilot thing, haven't even got it installed, but I should. There is a neovim plugin, I  should try it....
